name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Actions checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build affected apps
        run: npx nx affected --target=build --parallel=3 --ci --base=origin/master

      - name: Linting affected apps
        run: npx nx affected --target=lint --parallel=3 --ci --base=origin/master
