name: Обновление сайта

on:
  push:
    branches:
    - master
    - github-ci
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: lts/Jod
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build all apps
      run: npx nx run-many --target=build --all --parallel=3 --no-cloud

    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dist

    - name: Push to server
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        port: ${{ secrets.DEPLOY_PORT }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        source: "apps/store/browser/*"
        target: "html"
        strip_components: 3
