name: CI/CD

on:
  push:
    branches:
      - master
      - github-ci
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Actions checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build affected apps
        run: npx nx affected --target=build --parallel=3 --ci --base=origin/github-ci

      - name: Linting affected apps
        run: npx nx affected --target=lint --parallel=3 --ci --base=origin/github-ci

      - name: Push to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          source: "dist/browser/*"
          target: "html"
