name: Обновление сайта

on:
  push:
    branches:
    - master
    - github-ci
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: lts/Jod
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build affected apps
      if: github.event_name == 'push'
      run: npx nx affected --target=build --parallel=3 --ci --base=origin/github-ci --head=HEAD

    - name: Build all apps
      if: github.event_name == 'workflow_dispatch'
      run: npx nx run-many --target=build --all --parallel=3 --ci

    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
