name: Обновление сайта

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: lts/Jod
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Linting
      run: npm run lint:affected

    - name: Build affected apps
      if: github.event_name == 'push'
      run: npm run build:affected

    - name: Build all apps
      if: github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request'
      run: npm run build

    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dist

    - name: Push to server
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        port: ${{ secrets.DEPLOY_PORT }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        source: "apps/*"
        target: "~/html"
        strip_components: 1
